function OutTable = readHotDogs(filename,ignoreHour)
%OutTable = readHotDogs(filename)
%
%   Reads comma separated ASCII files generated by the HOT-DOGS site, 
%   for data collected during the Hawaii Ocean Time-series.
%   Data are transformed in a Matlab table including cast information,
%   depth (from pressure) and date in Matlab format.
%   Requirements: Matlab ver 2013b or above
%       Gibbs SeaWater (GSW) Oceanographic Toolbox of TEOS-10 available
%       from http://www.TEOS-10.org
%
%   INPUT: filename: the comma separated ASCII file produced by HOT-DOGS
%          ignoreHour (OPTIONAL): if 1 ignores time to compute date (DEFAULT = 0)
%
%   OUTPUT: OutTable: a Matlab table with columns:
%       cruise station cast bottle date depth var1 ... varn
%
%   VERSION HISTORY:
%       r0.11: added option to ignore hour (Oct 6, 2016)
%
% Benedetto Barone - Oct 6, 2016 - Revision 0.11

if nargin<2, ignoreHour = 0; end

% Read variable names and variable units
f = fopen(filename);
ln = fgetl(f);
varname = textscan(ln,'%s','Delimiter',',');
varname = varname{1};
ln = fgetl(f);
varunits = textscan(ln,'%s','Delimiter',',');
varunits = varunits{1};
fclose(f);

% Read data
rawdata = array2table(csvread(filename,2,0));
rawdata(:,end) = [];
rawdata.Properties.VariableNames = varname;
rawdata.Properties.VariableUnits = varunits;
rawdata = standardizeMissing(rawdata,-9);

% Cruise number, cast number and bottle number
cruise = fix(rawdata.botid/10000000);
station = fix(mod(rawdata.botid,10000000)/100000);
cast = fix(mod(rawdata.botid,100000)/100);
bottle = mod(rawdata.botid,100);

% Compute depth from pressure
depth = -gsw_z_from_p(rawdata.press,22.75);

% Compute date in matlab format
month = fix(rawdata.date/10000);
day = fix(mod(rawdata.date,10000)/100);
year = 1900 + mod(rawdata.date,100);
year(year<1950) = year(year<1950)+100; % years after 2000
if ignoreHour == 1
    hour = 0; minute = 0; second =0;
else
    hour = fix(rawdata.time/10000);
    minute = fix(mod(rawdata.time,10000)/100);
    second = mod(rawdata.time,100);
end
date = datenum(year,month,day,hour,minute,second);

% Create output table
OutTable = table(cruise,station,cast,bottle,date,depth);
OutTable.Properties.VariableUnits = {'#','#','#','#','Matlab format (HST)','m'};

% Add data variables
for i = 5:width(rawdata)
    OutTable = [OutTable rawdata(:,i)];
end

end

